### ISSUE TITLE
Crafting recipes don't exist

### ISSUE THREAD

**Issue by LeafDevMc** [Byllfighter/Avaritia-Lite#1]
Unless this is an intended feature please fix this,
also my version is 1.19.2

**Comment by cylian914** [comment]
it look like there is no code for having craft in the crafting table mods

**Comment by Paddy69** [comment]
can confirm that there are no crafting recipes in the 1.19.2 code, i decompiled it localy and its just gone
im gonna try to rip the recipes from an older version and frankinstain them in

**Comment by Byllfighter** [comment]
Recipes are using [java files](https://github.com/search?q=repo%3AByllfighter%2FAvaritia-Lite++path%3A%2F%5Esrc%5C%2Fmain%5C%2Fjava%5C%2Fnet%5C%2Fbullfighter%5C%2Favaritia%5C%2Fprocedures%5C%2FExtremeCraftingTableRecipe%2F&type=code) instead of json. They are exist.
