### ISSUE TITLE
Making a netherite singularity is impossible

### ISSUE THREAD

**Issue by RadCppkiller** [Byllfighter/Avaritia-Lite#3]
Due to an error in NeutroniumCompressorTickProcedure.java, inserting a netherite block into a neutronium compressor will display the material as Amethyst and refuse to accept any other netherite blocks. This is caused by the string here saying "material","Amethyst" instead of "material","Netherite"

![image](https://github.com/Byllfighter/Avaritia-Lite/assets/154546035/b4cae509-5869-4cc5-838c-25b9f86ccc1e)

**Comment by SonyStinks** [comment]
Indeed. Confirmed this with my own copy of the mod running on 1.20.1 with Forge 47.2.19. Searched the code on GitHub and it appears on Line 1104 of NeutroniumCompressorTickProcedure.java. Looks like a copy/paste oversight. Should be a quick fix.
There is no workaround for this other than compiling the mod from scratch with the altered line in place, but you can cheat in the singularity and toss a thousand blocks of netherite to feel fair...

**Comment by Byllfighter** [comment]
Sorry for late answer. This issue has already been fixed.
